tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "thoughtbot/formulae"

brew "git"
brew "rcm"
brew "tmux"
brew "vim"

cask "1password"
cask "balenaetcher"
cask "fork"
cask "google-backup-and-sync"
cask "google-chrome"
cask "iterm2"
cask "keepingyouawake"
cask "slack"
cask "vlc"
